# Generated by Django 2.1.7 on 2019-04-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
