# Generated by Django 2.1.7 on 2019-04-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0002_auto_20190403_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=50, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
